-- ==========================================
-- SCRIPT DE BASE DE DATOS PARA ORACLE
-- ==========================================

-- 1. ELIMINACIÓN DE TABLAS (Por si se vuelve a ejecutar)
BEGIN
  FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN (
    'DETALLE_COMPRAS', 'COMPRAS', 'DETALLE_VENTAS', 'VENTAS', 
    'PRODUCTOS', 'CATEGORIAS_IVA', 'CLIENTES', 'BITACORA', 
    'PERMISOS', 'MENUS', 'USUARIOS', 'ROLES'
  )) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

-- 2. ELIMINACIÓN DE VISTAS Y PROCEDIMIENTOS
BEGIN
  FOR v IN (SELECT view_name FROM user_views WHERE view_name = 'V_REPORTES_VENTAS') LOOP
    EXECUTE IMMEDIATE 'DROP VIEW ' || v.view_name;
  END LOOP;
  FOR p IN (SELECT object_name FROM user_objects WHERE object_type = 'PROCEDURE' AND object_name IN (
    'PRC_LOGIN_USUARIO', 'PRC_REGISTRO_USUARIO', 'PRC_VENTAS_TOTALES_CLIENTE', 
    'PRC_VENTAS_POR_FECHA', 'PRC_CRUD_CLIENTE'
  )) LOOP
    EXECUTE IMMEDIATE 'DROP PROCEDURE ' || p.object_name;
  END LOOP;
END;
/

-- 3. CREACIÓN DE TABLAS (DDL)

-- Tabla Roles
CREATE TABLE ROLES (
    idRol NUMBER(11) GENERATED BY DEFAULT AS IDENTITY (START WITH 10) PRIMARY KEY,
    nombre VARCHAR2(30) NOT NULL UNIQUE,
    descripcion VARCHAR2(100)
);

-- Tabla Usuarios
CREATE TABLE USUARIOS (
    idUsuario NUMBER(11) GENERATED BY DEFAULT AS IDENTITY (START WITH 10) PRIMARY KEY,
    usuario VARCHAR2(50) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    nombres VARCHAR2(100) NOT NULL,
    apellidos VARCHAR2(100) NOT NULL,
    correo VARCHAR2(100),
    telefono VARCHAR2(20),
    cedula VARCHAR2(10) NOT NULL UNIQUE,
    estado VARCHAR2(10) DEFAULT 'Activo' CHECK (estado IN ('Activo', 'Inactivo')),
    intentosFallidos NUMBER(11) DEFAULT 0 NOT NULL,
    bloqueadoHasta TIMESTAMP,
    idRol NUMBER(11) NOT NULL,
    fechaNacimiento DATE,
    fechaModificacion TIMESTAMP,
    CONSTRAINT fk_usuarios_roles FOREIGN KEY (idRol) REFERENCES ROLES(idRol)
);

-- Tabla Menus
CREATE TABLE MENUS (
    idMenu NUMBER(11) GENERATED BY DEFAULT AS IDENTITY (START WITH 30) PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    url VARCHAR2(100) NOT NULL,
    ordenMenu NUMBER(11),
    idMenuPadre NUMBER(11),
    activo NUMBER(1) DEFAULT 1 NOT NULL CHECK (activo IN (0, 1))
);

-- Tabla Permisos
CREATE TABLE PERMISOS (
    idPermiso NUMBER(11) GENERATED BY DEFAULT AS IDENTITY (START WITH 50) PRIMARY KEY,
    idRol NUMBER(11) NOT NULL,
    idMenu NUMBER(11) NOT NULL,
    CONSTRAINT fk_permisos_roles FOREIGN KEY (idRol) REFERENCES ROLES(idRol),
    CONSTRAINT fk_permisos_menus FOREIGN KEY (idMenu) REFERENCES MENUS(idMenu)
);

-- Tabla Bitacora (Auditoría)
CREATE TABLE BITACORA (
    idBitacora NUMBER(11) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idUsuario NUMBER(11),
    accion VARCHAR2(200),
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ip VARCHAR2(50),
    CONSTRAINT fk_bitacora_usuarios FOREIGN KEY (idUsuario) REFERENCES USUARIOS(idUsuario)
);

-- Tabla Clientes
CREATE TABLE CLIENTES (
    idCliente NUMBER(11) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula VARCHAR2(10) NOT NULL UNIQUE,
    nombres VARCHAR2(100) NOT NULL,
    apellidos VARCHAR2(100) NOT NULL,
    correo VARCHAR2(100),
    telefono VARCHAR2(20),
    direccion VARCHAR2(200)
);

-- Tabla Categorias IVA
CREATE TABLE CATEGORIAS_IVA (
    idCategoriaIva NUMBER(11) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    porcentaje NUMBER(5,2) NOT NULL
);

-- Tabla Productos
CREATE TABLE PRODUCTOS (
    idProducto NUMBER(11) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(50) NOT NULL UNIQUE,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(250),
    precio NUMBER(10,2) NOT NULL CHECK (precio >= 0),
    unidadMedida VARCHAR2(20),
    idCategoriaIva NUMBER(11) NOT NULL,
    stock NUMBER(10,2) DEFAULT 0.00 NOT NULL CHECK (stock >= 0),
    CONSTRAINT fk_productos_cativa FOREIGN KEY (idCategoriaIva) REFERENCES CATEGORIAS_IVA(idCategoriaIva)
);

-- Tabla Ventas
CREATE TABLE VENTAS (
    idVenta NUMBER(11) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numeroFactura VARCHAR2(20) NOT NULL UNIQUE,
    idCliente NUMBER(11) NOT NULL,
    idUsuario NUMBER(11) NOT NULL,
    subtotal NUMBER(10,2) NOT NULL,
    iva NUMBER(10,2) NOT NULL,
    total NUMBER(10,2) NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_ventas_clientes FOREIGN KEY (idCliente) REFERENCES CLIENTES(idCliente),
    CONSTRAINT fk_ventas_usuarios FOREIGN KEY (idUsuario) REFERENCES USUARIOS(idUsuario)
);

-- Tabla Detalle Ventas
CREATE TABLE DETALLE_VENTAS (
    idDetalleVenta NUMBER(11) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idVenta NUMBER(11) NOT NULL,
    idProducto NUMBER(11) NOT NULL,
    cantidad NUMBER(10,2) NOT NULL,
    precio NUMBER(10,2) NOT NULL,
    iva NUMBER(10,2) NOT NULL,
    total NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_detallev_ventas FOREIGN KEY (idVenta) REFERENCES VENTAS(idVenta) ON DELETE CASCADE,
    CONSTRAINT fk_detallev_productos FOREIGN KEY (idProducto) REFERENCES PRODUCTOS(idProducto)
);

-- Tabla Compras
CREATE TABLE COMPRAS (
    idCompra NUMBER(11) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idUsuario NUMBER(11) NOT NULL,
    subtotal NUMBER(10,2) NOT NULL,
    iva NUMBER(10,2) NOT NULL,
    total NUMBER(10,2) NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_compras_usuarios FOREIGN KEY (idUsuario) REFERENCES USUARIOS(idUsuario)
);

-- Tabla Detalle Compras
CREATE TABLE DETALLE_COMPRAS (
    idDetalleCompra NUMBER(11) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idCompra NUMBER(11) NOT NULL,
    idProducto NUMBER(11) NOT NULL,
    cantidad NUMBER(10,2) NOT NULL,
    precio NUMBER(10,2) NOT NULL,
    iva NUMBER(10,2) NOT NULL,
    total NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_detallec_compras FOREIGN KEY (idCompra) REFERENCES COMPRAS(idCompra) ON DELETE CASCADE,
    CONSTRAINT fk_detallec_productos FOREIGN KEY (idProducto) REFERENCES PRODUCTOS(idProducto)
);

-- 4. ÍNDICES OBLIGATORIOS (Indexación)
CREATE INDEX idx_usuarios_rol ON USUARIOS(idRol);
CREATE INDEX idx_clientes_apellidos ON CLIENTES(apellidos, nombres);
CREATE INDEX idx_productos_codigo ON PRODUCTOS(codigo);
CREATE INDEX idx_ventas_fecha ON VENTAS(fecha);

-- 5. VISTAS OBLIGATORIAS (Reportes Empresariales)
CREATE OR REPLACE VIEW V_REPORTES_VENTAS AS
SELECT 
    v.idVenta,
    v.numeroFactura,
    v.fecha,
    c.cedula AS cliente_cedula,
    c.nombres || ' ' || c.apellidos AS cliente_nombre,
    u.usuario AS vendedor,
    v.subtotal,
    v.iva,
    v.total
FROM VENTAS v
INNER JOIN CLIENTES c ON v.idCliente = c.idCliente
INNER JOIN USUARIOS u ON v.idUsuario = u.idUsuario;

-- 6. TRIGGERS OBLIGATORIOS

-- A. Trigger BEFORE INSERT → Validación de datos (ej. formato correo y cédula)
CREATE OR REPLACE TRIGGER TRG_USUARIOS_BI
BEFORE INSERT ON USUARIOS
FOR EACH ROW
BEGIN
    IF :NEW.correo IS NOT NULL AND NOT REGEXP_LIKE(:NEW.correo, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$') THEN
        RAISE_APPLICATION_ERROR(-20002, 'Formato de correo electrónico inválido.');
    END IF;
    IF LENGTH(:NEW.cedula) != 10 THEN
        RAISE_APPLICATION_ERROR(-20003, 'La cédula debe tener exactamente 10 dígitos.');
    END IF;
END;
/

-- B. Trigger AFTER UPDATE → Auditoría de cambios en usuarios
CREATE OR REPLACE TRIGGER TRG_USUARIOS_AU
AFTER UPDATE ON USUARIOS
FOR EACH ROW
BEGIN
    INSERT INTO BITACORA (idUsuario, accion, fecha, ip)
    VALUES (:NEW.idUsuario, 'Actualización de usuario: ' || :OLD.usuario || ' a ' || :NEW.usuario, SYSTIMESTAMP, 'localhost');
END;
/

-- C. Trigger BEFORE DELETE → Restricción por relaciones (no eliminar clientes con ventas)
CREATE OR REPLACE TRIGGER TRG_CLIENTES_BD
BEFORE DELETE ON CLIENTES
FOR EACH ROW
DECLARE
    v_cantidad NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cantidad FROM VENTAS WHERE idCliente = :OLD.idCliente;
    IF v_cantidad > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar el cliente porque tiene ventas registradas.');
    END IF;
END;
/

-- D. Trigger AFTER INSERT/UPDATE → Actualización automática de fecha de modificación
CREATE OR REPLACE TRIGGER TRG_USUARIOS_AIU
BEFORE INSERT OR UPDATE ON USUARIOS
FOR EACH ROW
BEGIN
    :NEW.fechaModificacion := SYSTIMESTAMP;
END;
/

-- 7. PROCEDIMIENTOS ALMACENADOS OBLIGATORIOS

-- A. Login de Usuario (15 parámetros)
CREATE OR REPLACE PROCEDURE PRC_LOGIN_USUARIO (
    p_usuario IN VARCHAR2,
    p_idUsuario OUT NUMBER,
    p_password OUT VARCHAR2,
    p_nombres OUT VARCHAR2,
    p_apellidos OUT VARCHAR2,
    p_correo OUT VARCHAR2,
    p_telefono OUT VARCHAR2,
    p_cedula OUT VARCHAR2,
    p_estado OUT VARCHAR2,
    p_intentosFallidos OUT NUMBER,
    p_bloqueadoHasta OUT VARCHAR2,
    p_idRol OUT NUMBER,
    p_rol OUT VARCHAR2,
    p_estaBloqueado OUT NUMBER,
    p_segundosRestantes OUT NUMBER
) AS
BEGIN
    SELECT u.idUsuario, u.password, u.nombres, u.apellidos, u.correo, u.telefono, u.cedula, u.estado, u.intentosFallidos, 
           TO_CHAR(u.bloqueadoHasta, 'YYYY-MM-DD HH24:MI:SS'), u.idRol, r.nombre,
           CASE WHEN u.bloqueadoHasta IS NOT NULL AND u.bloqueadoHasta > SYSTIMESTAMP THEN 1 ELSE 0 END,
           COALESCE(EXTRACT(SECOND FROM (u.bloqueadoHasta - SYSTIMESTAMP)), 0)
    INTO p_idUsuario, p_password, p_nombres, p_apellidos, p_correo, p_telefono, p_cedula, p_estado, p_intentosFallidos,
         p_bloqueadoHasta, p_idRol, p_rol, p_estaBloqueado, p_segundosRestantes
    FROM USUARIOS u
    INNER JOIN ROLES r ON u.idRol = r.idRol
    WHERE u.usuario = p_usuario AND u.estado = 'Activo';
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_idUsuario := NULL;
        p_password := NULL;
        p_nombres := NULL;
        p_apellidos := NULL;
        p_correo := NULL;
        p_telefono := NULL;
        p_cedula := NULL;
        p_estado := NULL;
        p_intentosFallidos := 0;
        p_bloqueadoHasta := NULL;
        p_idRol := NULL;
        p_rol := NULL;
        p_estaBloqueado := 0;
        p_segundosRestantes := 0;
END;
/

-- B. Registro de Usuario (con validación de duplicados)
CREATE OR REPLACE PROCEDURE PRC_REGISTRO_USUARIO (
    p_usuario IN VARCHAR2,
    p_password IN VARCHAR2,
    p_nombres IN VARCHAR2,
    p_apellidos IN VARCHAR2,
    p_correo IN VARCHAR2,
    p_telefono IN VARCHAR2,
    p_cedula IN VARCHAR2,
    p_idRol IN NUMBER,
    p_resultado OUT VARCHAR2
) AS
    v_existe NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_existe FROM USUARIOS WHERE usuario = p_usuario OR cedula = p_cedula;
    IF v_existe > 0 THEN
        p_resultado := 'ERROR_DUPLICADO';
    ELSE
        INSERT INTO USUARIOS (usuario, password, nombres, apellidos, correo, telefono, cedula, idRol, estado)
        VALUES (p_usuario, p_password, p_nombres, p_apellidos, p_correo, p_telefono, p_cedula, p_idRol, 'Activo');
        p_resultado := 'OK';
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        p_resultado := SQLERRM;
END;
/

-- C. Ventas Totales por Cliente
CREATE OR REPLACE PROCEDURE PRC_VENTAS_TOTALES_CLIENTE (
    p_idCliente IN NUMBER,
    p_total_ventas OUT NUMBER
) AS
BEGIN
    SELECT COALESCE(SUM(total), 0) INTO p_total_ventas 
    FROM VENTAS 
    WHERE idCliente = p_idCliente;
END;
/

-- D. Ventas por Rango de Fechas
CREATE OR REPLACE PROCEDURE PRC_VENTAS_POR_FECHA (
    p_fecha_inicio IN TIMESTAMP,
    p_fecha_fin IN TIMESTAMP,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT * FROM V_REPORTES_VENTAS
    WHERE fecha BETWEEN p_fecha_inicio AND p_fecha_fin
    ORDER BY fecha DESC;
END;
/

-- E. CRUD de Clientes mediante procedimiento (Optimizado para compatibilidad con PDO_OCI)
CREATE OR REPLACE PROCEDURE PRC_CRUD_CLIENTE (
    p_operacion IN VARCHAR2, -- 'C' (Create), 'U' (Update), 'D' (Delete)
    p_idCliente IN OUT NUMBER,
    p_cedula IN VARCHAR2 DEFAULT NULL,
    p_nombres IN VARCHAR2 DEFAULT NULL,
    p_apellidos IN VARCHAR2 DEFAULT NULL,
    p_correo IN VARCHAR2 DEFAULT NULL,
    p_telefono IN VARCHAR2 DEFAULT NULL,
    p_direccion IN VARCHAR2 DEFAULT NULL
) AS
BEGIN
    IF p_operacion = 'C' THEN
        INSERT INTO CLIENTES (cedula, nombres, apellidos, correo, telefono, direccion)
        VALUES (p_cedula, p_nombres, p_apellidos, p_correo, p_telefono, p_direccion)
        RETURNING idCliente INTO p_idCliente;
    ELSIF p_operacion = 'U' THEN
        UPDATE CLIENTES 
        SET cedula = NVL(p_cedula, cedula),
            nombres = NVL(p_nombres, nombres),
            apellidos = NVL(p_apellidos, apellidos),
            correo = NVL(p_correo, correo),
            telefono = NVL(p_telefono, telefono),
            direccion = NVL(p_direccion, direccion)
        WHERE idCliente = p_idCliente;
    ELSIF p_operacion = 'D' THEN
        DELETE FROM CLIENTES WHERE idCliente = p_idCliente;
    END IF;
END;
/

-- 8. VOLCADO DE DATOS BÁSICOS (DML)
INSERT INTO ROLES (idRol, nombre, descripcion) VALUES (1, 'Administrador', 'Control total del sistema');
INSERT INTO ROLES (idRol, nombre, descripcion) VALUES (2, 'Usuario', 'Acceso limitado');
INSERT INTO ROLES (idRol, nombre, descripcion) VALUES (3, 'Cliente', 'Puede comprar productos y acceder al inicio');

-- Contraseña encriptada para el administrador es 'admin' usando password_hash en PHP (Actualizada).
INSERT INTO USUARIOS (idUsuario, usuario, password, nombres, apellidos, correo, telefono, cedula, estado, idRol)
VALUES (2, 'admin', '$2y$10$i5wJ20d4ZE.v2BsaUVyhTOSnErm8QCckgh0zDoK6Yydh.ugTohne2', 'Alex', 'Administrador', 'admin@sistema.com', '0999999999', '0102030400', 'Activo', 1);

INSERT INTO CATEGORIAS_IVA (idCategoriaIva, nombre, porcentaje) VALUES (1, 'IVA 15%', 15.00);
INSERT INTO CATEGORIAS_IVA (idCategoriaIva, nombre, porcentaje) VALUES (2, 'IVA 0%', 0.00);

-- Menús básicos e iniciales en el Sistema
INSERT INTO MENUS (idMenu, nombre, url, ordenMenu, idMenuPadre, activo) VALUES (1, 'Inicio', 'view/dashboard.html', 1, NULL, 1);
INSERT INTO MENUS (idMenu, nombre, url, ordenMenu, idMenuPadre, activo) VALUES (2, 'Usuarios', '#', 2, NULL, 1);
INSERT INTO MENUS (idMenu, nombre, url, ordenMenu, idMenuPadre, activo) VALUES (3, 'Listar usuarios', 'view/usuarios/listar.php', 3, 2, 1);
INSERT INTO MENUS (idMenu, nombre, url, ordenMenu, idMenuPadre, activo) VALUES (4, 'Crear usuario', 'view/usuarios/create.php', 4, 2, 1);
INSERT INTO MENUS (idMenu, nombre, url, ordenMenu, idMenuPadre, activo) VALUES (11, 'Roles', '#', 5, NULL, 1);
INSERT INTO MENUS (idMenu, nombre, url, ordenMenu, idMenuPadre, activo) VALUES (12, 'Listar Roles', 'view/roles/listar.php', 6, 11, 1);
INSERT INTO MENUS (idMenu, nombre, url, ordenMenu, idMenuPadre, activo) VALUES (13, 'Crear Rol', 'view/roles/create.php', 7, 11, 1);
INSERT INTO MENUS (idMenu, nombre, url, ordenMenu, idMenuPadre, activo) VALUES (14, 'Permisos', 'view/permisos/asignar.php', 8, NULL, 1);
INSERT INTO MENUS (idMenu, nombre, url, ordenMenu, idMenuPadre, activo) VALUES (5, 'Clientes', 'view/clientes/listar.php', 9, NULL, 1);
INSERT INTO MENUS (idMenu, nombre, url, ordenMenu, idMenuPadre, activo) VALUES (6, 'Productos', 'view/productos/listar.php', 10, NULL, 1);
INSERT INTO MENUS (idMenu, nombre, url, ordenMenu, idMenuPadre, activo) VALUES (7, 'Ventas', '#', 11, NULL, 1);
INSERT INTO MENUS (idMenu, nombre, url, ordenMenu, idMenuPadre, activo) VALUES (8, 'Listar Ventas', 'view/ventas/listar.php', 12, 7, 1);
INSERT INTO MENUS (idMenu, nombre, url, ordenMenu, idMenuPadre, activo) VALUES (9, 'Registrar Venta', 'view/ventas/registrar.php', 13, 7, 1);
INSERT INTO MENUS (idMenu, nombre, url, ordenMenu, idMenuPadre, activo) VALUES (10, 'Reportes', 'view/reportes/dashboard.php', 14, NULL, 1);

-- Permisos para el Administrador (idRol = 1)
INSERT INTO PERMISOS (idRol, idMenu) VALUES (1, 1);
INSERT INTO PERMISOS (idRol, idMenu) VALUES (1, 2);
INSERT INTO PERMISOS (idRol, idMenu) VALUES (1, 3);
INSERT INTO PERMISOS (idRol, idMenu) VALUES (1, 4);
INSERT INTO PERMISOS (idRol, idMenu) VALUES (1, 5);
INSERT INTO PERMISOS (idRol, idMenu) VALUES (1, 6);
INSERT INTO PERMISOS (idRol, idMenu) VALUES (1, 7);
INSERT INTO PERMISOS (idRol, idMenu) VALUES (1, 8);
INSERT INTO PERMISOS (idRol, idMenu) VALUES (1, 9);
INSERT INTO PERMISOS (idRol, idMenu) VALUES (1, 10);
INSERT INTO PERMISOS (idRol, idMenu) VALUES (1, 11);
INSERT INTO PERMISOS (idRol, idMenu) VALUES (1, 12);
INSERT INTO PERMISOS (idRol, idMenu) VALUES (1, 13);
INSERT INTO PERMISOS (idRol, idMenu) VALUES (1, 14);

-- Permisos básicos para el Usuario (idRol = 2)
INSERT INTO PERMISOS (idRol, idMenu) VALUES (2, 1);
INSERT INTO PERMISOS (idRol, idMenu) VALUES (2, 5);
INSERT INTO PERMISOS (idRol, idMenu) VALUES (2, 6);
INSERT INTO PERMISOS (idRol, idMenu) VALUES (2, 7);
INSERT INTO PERMISOS (idRol, idMenu) VALUES (2, 8);
INSERT INTO PERMISOS (idRol, idMenu) VALUES (2, 9);

-- Permisos restringidos para el Cliente (idRol = 3)
INSERT INTO PERMISOS (idRol, idMenu) VALUES (3, 1);
INSERT INTO PERMISOS (idRol, idMenu) VALUES (3, 7);
INSERT INTO PERMISOS (idRol, idMenu) VALUES (3, 9);

COMMIT;